/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Sofia Romero
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
 
    HashTable tabla = null;
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Integrantes = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        SubirArchivo = new java.awt.Button();
        Integrantes1 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();

        jLabel1.setText("jLabel1");

        Integrantes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Integrantes.setForeground(new java.awt.Color(255, 255, 255));
        Integrantes.setText("Integrantes:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Bioinformática");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 170, 40));

        SubirArchivo.setLabel("Cargar Archivo");
        SubirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(SubirArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        Integrantes1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Integrantes1.setForeground(new java.awt.Color(255, 255, 255));
        Integrantes1.setText("Integrantes:");
        jPanel1.add(Integrantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 90, 30));

        label3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Sofia Romero");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        label4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Integrantes: ");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 2, 460, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
 * Maneja la accion del botón "Subir Archivo".
 * 
 * Este método permite al usuario seleccionar un archivo de texto (.txt) mediante un JFileChooser.
 * Si el archivo es válido, se lee el contenido, se divide en bloques de tres caracteres,
 * y se almacena en una tabla hash. Cada bloque se asocia con una instancia
 * de {@code Informacion}, que registra las ubicaciones donde aparece el bloque.
 * 
 * @param evt el evento de acción generado al hacer clic en el botón
 */
    private void SubirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirArchivoActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int respuesta = fileChooser.showOpenDialog(this);
        
        if(respuesta == JFileChooser.APPROVE_OPTION){
            java.io.File archivoSeleccionado = fileChooser.getSelectedFile();
            
            if (archivoSeleccionado.getName().toLowerCase().endsWith(".txt")) {
               JOptionPane.showMessageDialog(this, "Archivo TXT seleccionado: " + archivoSeleccionado.getAbsolutePath(), "Archivo Seleccionado", JOptionPane.INFORMATION_MESSAGE);
                
            }
             try (BufferedReader reader = new BufferedReader(
                    new InputStreamReader(new FileInputStream(archivoSeleccionado), StandardCharsets.UTF_8))
                ){
                    StringBuilder contenido = new StringBuilder();
                    String line;

                    while ((line = reader.readLine()) != null){
                        contenido.append(line.trim());
                    }
                    tabla = new HashTable(Math.round(contenido.length()/3));
                    
                    for (int i=0; i<contenido.length()-3; i+=3 ){
                        
                        String bloque = contenido.substring(i, i+3);
                        Informacion info = tabla.Buscar(bloque);
                        if(info == null){
                            info = new Informacion();
                            tabla.Agregar(bloque, info);
                            System.out.println("Bloque de 3: "+ bloque);
                        }
                        info.AgregarUbi(i);
                    
                    }
                    
                    
             } catch (IOException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        SegundaInterfaz SI = new SegundaInterfaz(tabla);
        SI.setVisible(true);
        SI.setLocationRelativeTo(null);
        this.setVisible(false);
        
    }//GEN-LAST:event_SubirArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
        java.awt.EventQueue.invokeLater(() -> {
            new Interfaz().setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Integrantes;
    private java.awt.Label Integrantes1;
    private java.awt.Button SubirArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
}
