package proyecto2;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sofia Romero
 */
public class SegundaInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form SegundaInterfaz
     */
    
    /** Tabla hash que contiene información procesada de tripletas. */
    public static HashTable tabla;
    
    /** Lista de aminoácidos con sus respectivas tripletas de codones. */
    Aminoacido[] listaAminoacidos = {
        new Aminoacido("Fenilalanina", new String[]{"TTT", "TTC"}),
        new Aminoacido("Leucina", new String[]{"TTA", "TTG", "CTT",
"CTC", "CTA", "CTG"}),
        new Aminoacido("Isoleucina", new String[]{"ATT", "ATC", "ATA"}),
        new Aminoacido("Metionina (Inicio)", new String[]{"ATG"}),
        new Aminoacido("Valina", new String[]{"GTT", "GTC", "GTA", "GTG"}),
        new Aminoacido("Serina", new String[]{"TCT", "TCC", "TCA",
"TCG", "AGT", "AGC"}),
        new Aminoacido("Prolina", new String[]{"CCT", "CCC", "CCA", "CCG"}),
        new Aminoacido("Treonina", new String[]{"ACT", "ACC", "ACA", "ACG"}),
        new Aminoacido("Alanina", new String[]{"GCT", "GCC", "GCA", "GCG"}),
        new Aminoacido("Tirosina", new String[]{"TAT", "TAC"}),
        new Aminoacido("Histidina", new String[]{"CAT", "CAC"}),
        new Aminoacido("Glutamina", new String[]{"CAA", "CAG"}),
        new Aminoacido("Asparagina", new String[]{"AAT", "AAC"}),
        new Aminoacido("Lisina", new String[]{"AAA", "AAG"}),
        new Aminoacido("Acido Aspartico", new String[]{"GAT", "GAC"}),
        new Aminoacido("Acido Glutamico", new String[]{"GAA", "GAG"}),
        new Aminoacido("Cisteina", new String[]{"TGT", "TGC"}),
        new Aminoacido("Triptofano", new String[]{"TGG"}),
        new Aminoacido("Arginina", new String[]{"CGT", "CGC", "CGA",
"CGG", "AGA", "AGG"}),
        new Aminoacido("Glicina", new String[]{"GGT", "GGC", "GGA", "GGG"}),
        new Aminoacido("Parada", new String[]{"TAA", "TAG", "TGA"})
    };
    
    /** Cadena que almacena la respuesta de la interfaz. */
    public static String respuesta;

    /**
     * Constructor de {@code SegundaInterfaz}.
     * 
     * Inicializa los componentes gráficos, calcula el total de tripletas
     * a partir de la lista de aminoácidos, las ordena alfabéticamente y las agrega
     * al componente {@code usuario} como opciones seleccionables.
     * 
     * @param tabla instancia de {@code HashTable} con la información genética procesada
     */
    public SegundaInterfaz(HashTable tabla) {
        initComponents();
        this.tabla =tabla;
        int totalTripletas =0;
        
        for (int i = 0; i < listaAminoacidos.length; i++) {
            totalTripletas += listaAminoacidos[i].tripletas.length;
        }
        
        String[] tripletas = new String[totalTripletas];
        int index = 0;
        
        for(int i=0; i< listaAminoacidos.length; i++){
            for(int j = 0; j< listaAminoacidos[i].tripletas.length; j++){
                System.out.println(listaAminoacidos[i].tripletas[j]);
                tripletas[index]= listaAminoacidos[i].tripletas[j];
                index++;
                
            }
        }
        
        for (int i = 0; i < tripletas.length - 1; i++) {
            for (int j = 0; j < tripletas.length - i - 1; j++) {
                if (tripletas[j].compareTo(tripletas[j + 1]) > 0) {
                    String temp = tripletas[j];
                    tripletas[j] = tripletas[j + 1];
                    tripletas[j + 1] = temp;
                }
            }
        }
        
        for(int i=0; i<tripletas.length; i++){
            usuario.addItem(tripletas[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        PatronesAlmacenados = new java.awt.Button();
        BuscarPatron = new java.awt.Button();
        MenosFrecuentes = new java.awt.Button();
        MasFrecuentes = new java.awt.Button();
        ReporteColisiones = new java.awt.Button();
        ListadoAminoacidos = new java.awt.Button();
        label2 = new java.awt.Label();
        usuario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText(" Bioinformatica Opciones");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        PatronesAlmacenados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PatronesAlmacenados.setLabel("Patrones Almacenados");
        PatronesAlmacenados.setName("Patrones Almacenados"); // NOI18N
        PatronesAlmacenados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatronesAlmacenadosActionPerformed(evt);
            }
        });
        jPanel1.add(PatronesAlmacenados, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        BuscarPatron.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BuscarPatron.setLabel("Buscar Patron");
        BuscarPatron.setName("BuscarPatron"); // NOI18N
        BuscarPatron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPatronActionPerformed(evt);
            }
        });
        jPanel1.add(BuscarPatron, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, -1));

        MenosFrecuentes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MenosFrecuentes.setLabel("Patron Menos Frecuentes");
        MenosFrecuentes.setName("MenosFrecuente"); // NOI18N
        MenosFrecuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenosFrecuentesActionPerformed(evt);
            }
        });
        jPanel1.add(MenosFrecuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        MasFrecuentes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MasFrecuentes.setLabel("Patron Mas Frecuentes");
        MasFrecuentes.setName("MasFrecuentes"); // NOI18N
        MasFrecuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasFrecuentesActionPerformed(evt);
            }
        });
        jPanel1.add(MasFrecuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        ReporteColisiones.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ReporteColisiones.setLabel("Reporte Colisones");
        ReporteColisiones.setName("ReporteColisiones"); // NOI18N
        ReporteColisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteColisionesActionPerformed(evt);
            }
        });
        jPanel1.add(ReporteColisiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        ListadoAminoacidos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ListadoAminoacidos.setLabel("Lista de Aminoacidos");
        ListadoAminoacidos.setName(""); // NOI18N
        ListadoAminoacidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoAminoacidosActionPerformed(evt);
            }
        });
        jPanel1.add(ListadoAminoacidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        label2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setName(""); // NOI18N
        label2.setText("Inserte el patron:");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Maneja la búsqueda de un patrón seleccionado por el usuario.
    * 
    * Este método obtiene la tripleta seleccionada desde el componente {@code usuario},
    * busca su información en la tabla hash, y genera una respuesta con la frecuencia
    * y ubicaciones del patrón si existe. Luego, muestra una nueva interfaz con los resultados.
    * 
    * @param evt el evento de acción generado al hacer clic en el botón de búsqueda
    */
    
    private void BuscarPatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPatronActionPerformed
        // TODO add your handling code here:
        respuesta = (String) (usuario.getSelectedItem());
        
        Informacion info = tabla.Buscar(respuesta);
        if(info == null){
            respuesta =("No se consiguio");
        }else{
            respuesta = ("La Frecuencia es: " + Integer.toString(info.getFrecuencia()));
            respuesta = respuesta + "\nUbicaciones\n";
            for(int i=0; i<info.getUbicaciones().length; i++){
                respuesta = respuesta + info.getUbicaciones()[i] + ", ";
            }
        }
        ResultadosInterfaz resultado = new ResultadosInterfaz(tabla, respuesta);
        resultado.setVisible(true);
        resultado.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BuscarPatronActionPerformed

    /**
    * Manejo de acción para generar un reporte de colisiones en la tabla hash.
    * 
    * Este método invoca el método {@code reporteColisiones()} de la instancia {@code tabla},
    * que devuelve un resumen de las colisiones ocurridas durante el almacenamiento de datos.
    * Luego, muestra una nueva interfaz con los resultados obtenidos.
    * 
    * @param evt el evento de acción generado al hacer clic en el botón de reporte
    */ 
    private void ReporteColisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteColisionesActionPerformed

        // TODO add your handling code here:
        respuesta = tabla.reporteColisiones(); 
        
        ResultadosInterfaz resultado = new ResultadosInterfaz(tabla, respuesta);
        resultado.setVisible(true);
        resultado.setLocationRelativeTo(null);
        this.setVisible(false);
        
    }//GEN-LAST:event_ReporteColisionesActionPerformed

    /**
    * Maneja para mostrar el patrón más frecuente en la tabla hash.
    * 
    * Este método invoca {@code obtenerMasFrecuente()} sobre la instancia {@code tabla},
    * que devuelve el nodo con mayor frecuencia de aparición. Si se encuentra un patrón,
    * se construye una respuesta con su clave, frecuencia y ubicaciones. Luego se muestra
    * una nueva interfaz con los resultados.
    * 
    * @param evt el evento de acción generado al hacer clic en el botón correspondiente
    */

    private void MasFrecuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasFrecuentesActionPerformed
        // TODO add your handling code here:
        
        HashNodo info = tabla.obtenerMasFrecuente();
        if(info == null){
            respuesta =("No se consiguio");
        }else{
            respuesta = ("El mas frecuente es: "+ info.clave + " con " + Integer.toString(info.info.getFrecuencia()));
            respuesta = respuesta + "\nUbicaciones\n";
            for(int i=0; i<info.info.getUbicaciones().length; i++){
                respuesta = respuesta + info.info.getUbicaciones()[i] + ", ";
            }
        }
        
        ResultadosInterfaz resultado = new ResultadosInterfaz(tabla, respuesta);
        resultado.setVisible(true);
        resultado.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_MasFrecuentesActionPerformed

    /**
    * Maneja la acción para generar un listado de tripletas agrupadas por aminoácido.
    * 
    * Este método utiliza la función {@code listarTripletasPorAminoacido()} de la tabla hash,
    * pasando como parámetro el arreglo {@code listaAminoacidos}. El resultado es una cadena
    * que agrupa las tripletas por cada aminoácido. Luego se muestra en una nueva interfaz.
    * 
    * @param evt el evento de acción generado al hacer clic en el botón correspondiente
    */

    private void ListadoAminoacidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoAminoacidosActionPerformed
        // TODO add your handling code here:
        
        respuesta = tabla.listarTripletasPorAminoacido(listaAminoacidos);
        
        ResultadosInterfaz resultado = new ResultadosInterfaz(tabla, respuesta);
        resultado.setVisible(true);
        resultado.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_ListadoAminoacidosActionPerformed

    /**
    * Maneja el evento para mostrar el patrón menos frecuente en la tabla hash.
    * 
    * Este método invoca {@code obtenerMenosFrecuente()} sobre la instancia {@code tabla},
    * que devuelve el nodo con menor frecuencia de aparición. Si se encuentra un patrón,
    * se construye una respuesta con su clave, frecuencia y ubicaciones. Luego se muestra
    * una nueva interfaz con los resultados y se oculta la actual.
    * 
    * @param evt el evento de acción generado al hacer clic en el botón correspondiente
    */
    private void MenosFrecuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenosFrecuentesActionPerformed
        // TODO add your handling code here:
        
        HashNodo info = tabla.obtenerMenosFrecuente();
        if(info == null){
            respuesta =("No se consiguio");
        }else{
            respuesta = ("El menos frecuente es: "+ info.clave + " con " + Integer.toString(info.info.getFrecuencia()));
            respuesta = respuesta + "\nUbicaciones\n";
            for(int i=0; i<info.info.getUbicaciones().length; i++){
                respuesta = respuesta + info.info.getUbicaciones()[i] + ", ";
            }
        }
        
        ResultadosInterfaz resultado = new ResultadosInterfaz(tabla, respuesta);
        resultado.setVisible(true);
        resultado.setLocationRelativeTo(null);
        this.setVisible(false);
        
    }//GEN-LAST:event_MenosFrecuentesActionPerformed

    /**
    * Muestra todos los patrones almacenados en la tabla hash.
    * 
    * Este método invoca {@code tabla.todos()} para obtener una representación textual
    * de todos los patrones registrados. Luego, crea una nueva instancia de {@code ResultadosInterfaz}
    * para mostrar dicha información al usuario, ocultando la interfaz actual.
    * 
    * @param evt el evento de acción generado al hacer clic en el botón correspondiente
    */

    private void PatronesAlmacenadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatronesAlmacenadosActionPerformed
        // TODO add your handling code here:
        
        respuesta = tabla.todos();
        
        ResultadosInterfaz resultado = new ResultadosInterfaz(tabla, respuesta);
        resultado.setVisible(true);
        resultado.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_PatronesAlmacenadosActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundaInterfaz(tabla).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BuscarPatron;
    private java.awt.Button ListadoAminoacidos;
    private java.awt.Button MasFrecuentes;
    private java.awt.Button MenosFrecuentes;
    private java.awt.Button PatronesAlmacenados;
    private java.awt.Button ReporteColisiones;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JComboBox<String> usuario;
    // End of variables declaration//GEN-END:variables
}
