package proyecto2;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sofia Romero
 */
public class SegundaInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form SegundaInterfaz
     */
    
    
    public SegundaInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        PatronesAlmacenados = new java.awt.Button();
        BuscarPatron = new java.awt.Button();
        MenosFrecuentes = new java.awt.Button();
        MasFrecuentes = new java.awt.Button();
        ReporteColisiones = new java.awt.Button();
        ListadoAminoacidos = new java.awt.Button();
        textField1 = new java.awt.TextField();
        label2 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText(" Bioinformatica Opciones");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        PatronesAlmacenados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PatronesAlmacenados.setLabel("Patrones Almacenados");
        PatronesAlmacenados.setName("Patrones Almacenados"); // NOI18N
        PatronesAlmacenados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatronesAlmacenadosActionPerformed(evt);
            }
        });
        jPanel1.add(PatronesAlmacenados, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        BuscarPatron.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BuscarPatron.setLabel("Buscar Patron");
        BuscarPatron.setName("BuscarPatron"); // NOI18N
        BuscarPatron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPatronActionPerformed(evt);
            }
        });
        jPanel1.add(BuscarPatron, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, -1));

        MenosFrecuentes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MenosFrecuentes.setLabel("Patron Menos Frecuentes");
        MenosFrecuentes.setName("MenosFrecuente"); // NOI18N
        MenosFrecuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenosFrecuentesActionPerformed(evt);
            }
        });
        jPanel1.add(MenosFrecuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        MasFrecuentes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MasFrecuentes.setLabel("Patron Mas Frecuentes");
        MasFrecuentes.setName("MasFrecuentes"); // NOI18N
        MasFrecuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasFrecuentesActionPerformed(evt);
            }
        });
        jPanel1.add(MasFrecuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        ReporteColisiones.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ReporteColisiones.setLabel("Reporte Colisones");
        ReporteColisiones.setName("ReporteColisiones"); // NOI18N
        ReporteColisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteColisionesActionPerformed(evt);
            }
        });
        jPanel1.add(ReporteColisiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        ListadoAminoacidos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ListadoAminoacidos.setLabel("Lista de Aminoacidos");
        ListadoAminoacidos.setName(""); // NOI18N
        ListadoAminoacidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoAminoacidosActionPerformed(evt);
            }
        });
        jPanel1.add(ListadoAminoacidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));
        jPanel1.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 20));

        label2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setName(""); // NOI18N
        label2.setText("Inserte el patron:");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarPatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPatronActionPerformed
        // TODO add your handling code here:
        
        ResultadosInterfaz resultado = new ResultadosInterfaz();
        resultado.setVisible(true);
        resultado.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BuscarPatronActionPerformed

    private void ReporteColisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteColisionesActionPerformed

        // TODO add your handling code here:
        ResultadosInterfaz resultado = new ResultadosInterfaz();
        resultado.setVisible(true);
        resultado.setLocationRelativeTo(null);
        this.setVisible(false);
        
    }//GEN-LAST:event_ReporteColisionesActionPerformed

    private void MasFrecuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasFrecuentesActionPerformed
        // TODO add your handling code here:
        ResultadosInterfaz resultado = new ResultadosInterfaz();
        resultado.setVisible(true);
        resultado.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_MasFrecuentesActionPerformed

    private void ListadoAminoacidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoAminoacidosActionPerformed
        // TODO add your handling code here:
        ResultadosInterfaz resultado = new ResultadosInterfaz();
        resultado.setVisible(true);
        resultado.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_ListadoAminoacidosActionPerformed

    private void MenosFrecuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenosFrecuentesActionPerformed
        // TODO add your handling code here:
        ResultadosInterfaz resultado = new ResultadosInterfaz();
        resultado.setVisible(true);
        resultado.setLocationRelativeTo(null);
        this.setVisible(false);
        
    }//GEN-LAST:event_MenosFrecuentesActionPerformed

    private void PatronesAlmacenadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatronesAlmacenadosActionPerformed
        // TODO add your handling code here:
        ResultadosInterfaz resultado = new ResultadosInterfaz();
        resultado.setVisible(true);
        resultado.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_PatronesAlmacenadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundaInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BuscarPatron;
    private java.awt.Button ListadoAminoacidos;
    private java.awt.Button MasFrecuentes;
    private java.awt.Button MenosFrecuentes;
    private java.awt.Button PatronesAlmacenados;
    private java.awt.Button ReporteColisiones;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
